### ISSUE TITLE
Problem with gnucash file conversion

### ISSUE THREAD

**Issue by rfaridi** [MatzeB/pygnucash#10]
I compiled latest gnucash (2.6.16)  from source with dbi conversion enabled. From gnucash  I could save as sqlite3 but the files were saved as "myfile.gnucash"  not "myfile.sqlite3".  But I don't know whether it will have sqlite3 extension in the first place when saved. Anyway, I went ahead and ran the python script  "gnucash2ledger.py"     downloaded from "https://github.com/MatzeB/pygnucash"  in the following manner:

python2.7  gnucash2ledger.py myfile.gnucash print > test.txt

The error came through is as follows:

Traceback (most recent call last):
  File "gnucash2ledger.py", line 35, in <module>
    data = gnucash.read_file(sys.argv[1])
AttributeError: 'module' object has no attribute 'read_file'

I noticed in the script page that it says that it requires python 2.7 with sqlite3 module enabled.  After some search I did the following to enable sqlite3:

sudo apt-get install sqlite3 libsqlite3-dev

sudo pip install pysqlite

But no luck so far.

**Comment by MatzeB** [comment]
Hmm odd. The only way I could explain this behavior is if there is some other python package on your system called `gnucash`. As an experiment could you start python2.7 somewhere outside(!) the pygnucash directory and type `import gnucash`. This results in "ImportError: No module named gnucash" on my system. If it works for you then it would be interesting to do `gnucash.__file__` to learn where the other gnucash python module is coming from.

**Comment by rfaridi** [comment]
I also installed a package called python-gnucash. Otherwise, it produced the following error:

Traceback (most recent call last):
  File "gnucash2ledger.py", line 6, in <module>
    import gnucash
ImportError: No module named gnucash

After I installed python-gnucash, the above error was gone but the above mentioned error  occurred.
